### ISSUE TITLE
Awesome work, however.....

### ISSUE THREAD

**Issue by mikkelzzz3** [nazwa/Free-Postcode-Lottery-Checker#1]
I just tried getting this to work, but I could not. I think it might be out of date, and not compatible with the site anymore. Also there are a lot more "lotteries" which are new, which the checker is not configured to check.

**Comment by nazwa** [comment]
Hey @mikkelzzz3 

You're right - I've stopped using it around a year ago. I was moving things to a new server and I think I forgot about this one completely. 

I'm not familiar with the current structure of FPL, but I'd expect it to be trivial to update the checkers.

Also I've noticed that some of the imports refer to the old bitbucket based repo.

Feel free to modify it as much as you want 👍

**Comment by mikkelzzz3** [comment]
Oh well, I do IT, but I have almost 0% programming skills. I will just have to check it the manual way then ;)

**Comment by mikkelzzz3** [comment]
Just so you know though, Googling "Free post code lottery checker" in Google, and your project is #1 result :D

**Comment by nazwa** [comment]
Haha no way! Maybe it's worth updating it... For the fame and glory 🏆

**Comment by nazwa** [comment]
Looks like they made it even easier now. I'll look into upgrading this at some point soon

**Comment by mikkelzzz3** [comment]
Cool thank you, that would be great, and also an installatin guide for dummies xD
